---
- name: Descargar activo desde GitHub usando ApiRest
  hosts: localhost
  vars:
    github_token: "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"
    owner: "BAC-Credomatic"
    repo: "ecsp-pasarelas-wcf"
  tasks:
    - name: Obtener el ultimo release creado en GitHub
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ owner }}/{{ repo }}/releases/latest
        method: GET
        headers:
          Authorization: "Bearer {{ github_token }}"
          accept: "application/vnd.github.v3+json"
      delegate_to: localhost
      register: release_info

    - name: Resultado de la consulta
      ansible.builtin.debug:
        msg: "El resultado de la consulta es: {{ release_info.json }}"

    - name: Extraer URL de descarga
      ansible.builtin.set_fact:
        asset_api_url: "{{ release_info.json.assets[0].url }}"

    - name: Descargar archivo desde GitHub
      when: release_info.json.assets | length > 0
      ansible.builtin.uri:
        url: "{{ asset_api_url }}"
        method: GET
        headers:
          Authorization: 'Bearer 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'
          Accept: 'application/vnd.github.v3+json'
        dest: /tmp/archivodeinstalacion.zip
        mode: '0644'
      delegate_to: localhost
      register: download_result

    - name: Resultado de la descarga
      ansible.builtin.debug:
        msg: "El resultado de la descarga es: {{ download_result }}"

- name: Copiar archivo a servidores destino
  hosts: servidores_destino
  tasks:
    - name: Copiar archivo al servidor destino
      ansible.builtin.copy:
        src: /tmp/archivodeinstalacion.zip
        dest: C:/tmp/archivodeinstalacion.zip
        mode: '0644'

    - name: Descomprimir archivo
      community.windows.win_unzip:
        src: C:/tmp/archivodeinstalacion.zip
        dest: C:/tmp/
        creates: c:/tmp
