---
- name: Extraer direcciones IP y nombres de servidores desde un PDF
  hosts: localhost
  tasks:
    - name: Convertir PDF a archivo de texto
      command: "pdftotext /ruta/al/archivo/Plan-de-Montaje-PN-0014154_V4-2.pdf /tmp/output.txt"
      register: pdf_conversion

    - name: Verificar que la conversión fue exitosa
      debug:
        msg: "Conversión exitosa: {{ pdf_conversion }}"

    - name: Leer el archivo de texto resultante
      slurp:
        src: /tmp/output.txt
      register: file_content

    - name: Decodificar contenido del archivo
      set_fact:
        decoded_content: "{{ file_content.content | b64decode }}"

    - name: Extraer direcciones IP usando expresiones regulares
      set_fact:
        ips: "{{ decoded_content | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"

    - name: Extraer nombres de servidores usando expresiones regulares
      set_fact:
        servers: "{{ decoded_content | regex_findall('[A-Z0-9]+\\s*\\([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\)') }}"

    - name: Mostrar las direcciones IP encontradas
      debug:
        msg: "Direcciones IP encontradas: {{ ips }}"

    - name: Mostrar los nombres de servidores encontrados
      debug:
        msg: "Nombres de servidores encontrados: {{ servers }}"
